//
export const GET_RESTAURANT_DETAILS_LOADING = "GET_RESTAURANT_DETAILS_LOADING";
export const GET_RESTAURANT_DETAILS_SUCCESS = "GET_RESTAURANT_DETAILS_SUCCESS";
export const GET_RESTAURANT_DETAILS_ERROR = "GET_RESTAURANT_DETAILS_ERROR";
//
export const ADD_RESTAURANT_DETAILS_LOADING = "ADD_RESTAURANT_DETAILS_LOADING";
export const ADD_RESTAURANT_DETAILS_SUCCESS = "ADD_RESTAURANT_DETAILS_SUCCESS";
export const ADD_RESTAURANT_DETAILS_ERROR = "ADD_RESTAURANT_DETAILS_ERROR";
//
export const UPDATE_RESTAURANT_DETAILS_LOADING = "UPDATE_RESTAURANT_DETAILS_LOADING";
export const UPDATE_RESTAURANT_DETAILS_SUCCESS = "UPDATE_RESTAURANT_DETAILS_SUCCESS";
export const UPDATE_RESTAURANT_DETAILS_ERROR = "UPDATE_RESTAURANT_DETAILS_ERROR";
//
export const DELETE_RESTAURANT_DETAILS_LOADING = "DELETE_RESTAURANT_DETAILS_LOADING";
export const DELETE_RESTAURANT_DETAILS_SUCCESS = "DELETE_RESTAURANT_DETAILS_SUCCESS";
export const DELETE_RESTAURANT_DETAILS_ERROR = "DELETE_RESTAURANT_DETAILS_ERROR";


//Restaurant  RESTAURANT